services:
  - type: web
    name: my-node-app
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    build:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install pandas